### ISSUE TITLE
Improve tool chain / StarterCmd

### ISSUE THREAD

**Issue by DonatJR** [SharkCagey/HTWG_shark_cage#10]
* find a better name for the `StarterCmd` app 
* maybe rewrite it in C# for easier UI development
* check if `SharkCage` is installed / deployed and if service already runs, if not start it
* functionality: let the user select a config file (table with all recent selected entries?) instead of the `.exe` like right now & check binary signature / hash before starting it  (this point should potentially be done by the executing app, i.e. the cage service)

**Comment by SailReal** [comment]
This issue is solved, right?

**Comment by SailReal** [comment]
Super hot 👍
