### ISSUE TITLE
Reconfigure access rights to match paper

### ISSUE THREAD

**Issue by bencikpeter** [SharkCagey/HTWG_shark_cage#102]
At  a glance... the access rights in a paper seem a lot more precise and thought through.... we, on the other hand just use a simplistic `GENERIC_ALL` and similar... I suggest doing it the other way around... configure the access rights as they are on the paper and see if it works

**Comment by SailReal** [comment]
Fixed with: https://github.com/SharkCagey/HTWG_shark_cage/pull/105
