### ISSUE TITLE
Shutdown: Close caged app / determine when cage is no longer needed

### ISSUE THREAD

**Issue by DonatJR** [SharkCagey/HTWG_shark_cage#12]
- [X] waiting for process handle to determine when to switch back to default desktop could maybe be improved #50 
- [X] make cage closable from inside (button in `labeller`-app / next to token?) _implemented witch #3_

**Comment by DonatJR** [comment]
making the cage closable from outside should be avoided I think, it could be misused

**Comment by SailReal** [comment]
This issue can be closed now due to #50, right?

**Comment by DonatJR** [comment]
YES :)
