### ISSUE TITLE
gitignore improvements

### ISSUE THREAD

**Issue by DonatJR** [SharkCagey/HTWG_shark_cage#19]
* make gitignore a whitelist instead of a blacklist
* check if we can remove some files / folders from repository (e.g. ipch stuff)
* clean up current entries

**Comment by SailReal** [comment]
lalala

**Comment by SailReal** [comment]
lala2

**Comment by SailReal** [comment]
lalala

**Comment by SailReal** [comment]
You can show which files are ignored (and changed) using the following command: `git ls-files --others -i --exclude-standard`
