### ISSUE TITLE
Terminate process on secure desktop

### ISSUE THREAD

**Issue by langweg** [SharkCagey/HTWG_shark_cage#32]
Processes on the secure desktop should all be terminated once the secure desktop is no longer in use. The reason is that the secure desktop might be used by two different applications in sequence. If the first application still has access to the secure desktop when the second application is executed, then the first could interfere with the second.
An alternative approach could be to create a new secure desktop every time the secure desktop is invoked for a new application so that a secure desktop is only used by a single applicqation and the desktop is only removed when the user logs off.

(Did not check if this issue is duplicated by an existing one.)

**Comment by DonatJR** [comment]
The current implementation already uses a new secure desktop for every single application, thus there can not be any information leak between applications on consecutive invokes of the secure desktop.

**Comment by SailReal** [comment]
As discussed in the team meeting today, this issue can be closed because of the argumentation of @DonatJR
