### ISSUE TITLE
Configuration application

### ISSUE THREAD

**Issue by langweg** [SharkCagey/HTWG_shark_cage#33]
The configuration of the secure desktop should be maintained by a configuration application that allows to:
- select which applications can be executed on the the secure desktop
- set which picture is shown per application on the secure desktop
- take a picture/video with the integrated camera to be shown together with an application on the secure desktop
- evaluate the log file when and how often an application has been executed on the secure desktop

(Did not check if this issue is duplicated by an existing one.)

**Comment by DonatJR** [comment]
this is also already in progress (#11), I copied your text to keep the information
