### ISSUE TITLE
ACLs for configuration files

### ISSUE THREAD

**Issue by langweg** [SharkCagey/HTWG_shark_cage#34]
All configuration files should at all times (creation, modification, retrieval, backup) be protected by suitable ACLs. The ACL should ensure that only the configuration application can modify the secure desktop configuration. Members of the Administrators group may read, but not modify, the configuration.
The ACL for a picture file should ensure that only the configuration application can modify the file and that only the cage service (and/or the cage labeller) can read the file. Members of the Administrators group must not be able to read the file.

(Did not check if this issue is duplicated by an existing one.)

**Comment by DonatJR** [comment]
this should already be included in #13 (I copied your text to keep the relevant information)
