### ISSUE TITLE
ACLs for processes

### ISSUE THREAD

**Issue by langweg** [SharkCagey/HTWG_shark_cage#35]
All processes that belong to the Shark Cage application must be executed with ACLs that disallow other processes to read or modify the process memory and that disallow injection of code into these applications.

https://msdn.microsoft.com/en-us/library/windows/desktop/ms684880(v=vs.85).aspx

(Did not check if this issue is duplicated by an existing one.)

**Comment by DonatJR** [comment]
this should already be included in #13 (I copied your text to keep the relevant information)
