### ISSUE TITLE
Upload application to Microsoft store

### ISSUE THREAD

**Issue by SailReal** [SharkCagey/HTWG_shark_cage#41]
First check what are the dependencies to publish an app into the Microsoft store and if it is possible in general (e.g. because of the token manipulation etc.).

**Comment by DaeVo** [comment]
"Apps must continue to run and remain responsive to user input. Apps must shut down gracefully and not close unexpectedly. The app must handle exceptions raised by any of the managed or native system APIs and remain responsive to user input after the exception is handled."

I couldn't find any restriction in the official policies that would specifically rule out sharkcage to be distributed via the Microsoft Store. The policy I cited above is probably the toughest requirement as it's hard to thoroughly test the app for all possible errors during development. Should we consider adding something like unit tests or would that be overkill?

**Comment by DonatJR** [comment]
I also think getting the token manipulation stuff on the store will be hard / impossible even if it is not explicitely mentioned in the requirements.

Nevertheless, unit tests are always a good idea if we have the capacity to implement them! 👍

**Comment by SailReal** [comment]
For the unit tests, created a new issue https://github.com/SharkCagey/HTWG_shark_cage/issues/46 if we have the time, it would be wonderful to implement them 😍
