### ISSUE TITLE
Remove whitespaces from all project dirs

### ISSUE THREAD

**Issue by SailReal** [SharkCagey/HTWG_shark_cage#5]
e.g. `Shark Cage`

**Comment by baWedekind** [comment]
@SailReal It should work now, please double check if you have time.

**Comment by SailReal** [comment]
maybe create a PR to give the whole team a chance to have a look at your changes.

**Comment by baWedekind** [comment]
as you wish

**Comment by SailReal** [comment]
Close due to https://github.com/SharkCagey/HTWG_shark_cage/pull/20#issuecomment-387050677
