### ISSUE TITLE
Start Configurator in cage

### ISSUE THREAD

**Issue by SailReal** [SharkCagey/HTWG_shark_cage#55]
![img_20180620_162630](https://user-images.githubusercontent.com/1786772/41673090-0883672e-74bc-11e8-9685-7cceb5a6026d.jpeg)

**Comment by DonatJR** [comment]
=> Deploy a .sconfig file which starts the Configurator Tool (setup has to change app_path to install_dir)
=> CageConfigurator has to check the ACLs of the current desktop, if not on cage desktop it has to send a message to the server to restart itself on the secure desktop (using the config mentioned above)

**Comment by DonatJR** [comment]
I added the config and some work needed later to detect on which cage the configurator was opened on https://github.com/SharkCagey/HTWG_shark_cage/tree/55-config-in-cage

The config needs to be replaced with one protected by the proper ACLs before finishing the project

**Comment by DonatJR** [comment]
Added the ability to check for ACL of the current desktop to configurator. But these ACLs first have to be set correctly to continue -> blocked by #13

**Comment by DonatJR** [comment]
done with #95
