### ISSUE TITLE
Sign application using yubikey

### ISSUE THREAD

**Issue by SailReal** [SharkCagey/HTWG_shark_cage#57]
Using the inserted Yubikey, we are now able to sign our applications  using the following command:

`signtool sign /sha1 ADBE74BD39789DD111815DE59C60D715143E4620 SharkCage.msi`

![screen shot 2018-06-27 at 8 18 50 pm](https://user-images.githubusercontent.com/1786772/41992048-b63d3a3a-7a47-11e8-94de-3a44be6ef8ba.png)

![screen shot 2018-06-27 at 8 29 30 pm](https://user-images.githubusercontent.com/1786772/41992484-dda5157e-7a48-11e8-8f4b-30849cc12cca.png)

#27

**Comment by SailReal** [comment]
Better use `signtool sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /sha1 ADBE74BD39789DD111815DE59C60D715143E4620 SharkCage.msi` to also assign a timestamp und use SHA256

**Comment by DonatJR** [comment]
We should also use the `/d` switch to have the UAC prompt display a proper name: 
```
/d Desc | Specifies a description of the signed content.
```
https://stackoverflow.com/questions/4315840/the-uac-prompt-shows-a-temporary-random-program-name-for-msi-can-the-correct-na
https://docs.microsoft.com/en-us/windows/desktop/seccrypto/signtool

**Comment by SailReal** [comment]
> We should also use the /d

Nice, works 👍
