### ISSUE TITLE
Json parsing crash

### ISSUE THREAD

**Issue by bencikpeter** [SharkCagey/HTWG_shark_cage#67]
When trying to launch self-built applications through shark cage, the cage configurator assigns null to application name
```json
{
  "application_name": null,
```

this, however crashes in `SharedFuncitons.cpp::ParseStartProcessMessage` at line 81

`auto application_name = json_config[APPLICATION_NAME_PROPERTY].get<std::string>();`

with output:

```
Could not parse json: Unknown exception
Could not process start process message

```

**Comment by DonatJR** [comment]
Riiight, I'm currently getting the name with the `FileDescription` of the file. If the description is not set the name will be null. Do you agree using the binary name (with / without extension?) would be a suitable fallback?
