### ISSUE TITLE
Check ACL of config file before starting cage

### ISSUE THREAD

**Issue by DonatJR** [SharkCagey/HTWG_shark_cage#75]
@SailReal any additional notes you have taken during the meeting regarding this?

**Comment by SailReal** [comment]
@DonatJR I wrote down that we could make in the Cage Configurator only the configs with the correct ACLs selectable (we can hide the rest).

**Comment by bencikpeter** [comment]
@SailReal I recommend greying out and making them unclickable instead. Straight out hiding is confusing

**Comment by DonatJR** [comment]
In my opinion the best solution is to not let them be opened in the Configurator / Chooser in the first place. Both applications can just inform the user about mismatching access rights upon opening an incorrect config file. This additionally gives the user a hint that he potentially has software on his machine which tries to mimic our config files.
