### ISSUE TITLE
Changing the order of process creation

### ISSUE THREAD

**Issue by SailReal** [SharkCagey/HTWG_shark_cage#79]
Maybe we should switch the order of the process creation: first create the (optional) additional app and then the main app so that the main app is on the screen when switching to the cage desktop and not the additional app.

@DonatJR @baWedekind what to you think about that?
Should be solved in a few minutes and only switching a few lines of code...

**Comment by DonatJR** [comment]
The issue is that one app covers the other completely, isn't it? Maybe we should rather open the main app fullscreen and the optional one normally so both are visible?

**Comment by SailReal** [comment]
Yeah, this would also solve the issue 👍. Something like this would be nice:
![screen shot 2018-07-23 at 1 18 48 pm](https://user-images.githubusercontent.com/1786772/43073775-0cc4967c-8e7b-11e8-803f-abb0b7223a42.png)

**Comment by DonatJR** [comment]
we thought it would be nicer than seeing the black background. but this point might now be moot with #74

**Comment by DonatJR** [comment]
should be done with #84
